---
title: "Dynamic report"
output: html_document
---

```{r include=FALSE}
library(dygraphs)
library(xts)
library(dplyr)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE)
```

# Timeseries plots

```{r}

plots[[1]] 

plots[[2]] 

plots[[3]] 

plots[[4]]

```

# Data quality based on Interbeat Intervals available

```{r}
data <- analysis$data

if (!is.null(data$IBI)) {
  
  knitr::asis_output("# IBI Data quality\\n")

  ibi_data <- xts(data$IBI$IBI, order.by = data$IBI$DateTime)

  dygraph(ibi_data, height = 200, width = 900, ylab = "Available ibi's") |>
    dyOptions(colors = "#f94144", drawPoints = TRUE,
              pointSize = 2) |>
    dyAxis(name = 'x', valueRange = c(data$EDA[[functions$get_datetime_column(data$EDA)]][1],
                                      tail(data$EDA[[functions$get_datetime_column(data$EDA)]], n=1)))
}

```


# Data quality based on EDA artifact detection

```{r}
eda_bin_plot_data <- thicken(analysis$eda_bin, interval = "1 min", colname = "datetime_1min") |>
  group_by(datetime_1min) |>
  summarize(frac_bad_data = mean(label == -1))

x_data <- xts(select(eda_bin_plot_data, datetime_1min, frac_bad_data), order.by = eda_bin_plot_data[[1]])

dygraph(x_data, height = 200, width = 900, ylab = "Fraction bad data") |>
  dyOptions(colors = "#f94144")

```

# Calendar events

```{r chunck-label, eval=TRUE}

kable(calendar, format = "html") |>
  kable_styling()

```


# Analysis output

```{r eval=TRUE, warning=FALSE}

functions$analysis_summary_table(analysis) |>
  kable(format = "html", digits = 2) |>
  kable_styling()

```


