visualisation:
  eda:
    yrange: [0,20]
    color: "#1874CD"
  hr:
    yrange: [40, 200]
    color: "#FF7F00"
  temp:
    yrange: [24, 38]
    color: "#458B00"
  move:
    e4:
      raw:
        yrange: [0.98, 1.25]
        color: "#68228B"
        custom_y: 1.07
    embrace-plus:
      raw:
        yrange: [0.98, 1.25]
        color: "#68228B"
        custom_y: 0.5
      aggregated:
        yrange: [0.98, 1.25]
        color: "#68228B"
        custom_y: 0.5
    nowatch:
      aggregated:
        yrange: [0.98, 1.25]
        color: "#68228B"
        custom_y: 0.5
  default_color: "blue"
